import type { BuildingSpec } from "./types";
import { WONDERS } from "./wonders";

/** Data-driven building catalog: ≥15 types per age; costs only use each age's resources. */
export const BUILDINGS: BuildingSpec[] = [
  // stone
  { type: "hut", age: "stone", cost: { wood: 20 }, buildSeconds: 30, houses: 2 },
  { type: "campfire", age: "stone", cost: { wood: 10, stone: 5 }, buildSeconds: 15 },
  { type: "granary", age: "stone", cost: { wood: 30, stone: 10 }, buildSeconds: 40 },
  { type: "toolmaker", age: "stone", cost: { wood: 15, stone: 15 }, buildSeconds: 35 },
  { type: "storyteller-circle", age: "stone", cost: { wood: 15, stone: 10 }, buildSeconds: 25 },
  { type: "flint-knapper", age: "stone", cost: { stone: 20 }, buildSeconds: 30 },
  { type: "drying-rack", age: "stone", cost: { wood: 12 }, buildSeconds: 20 },
  { type: "fishing-hut", age: "stone", cost: { wood: 18 }, buildSeconds: 25 },
  { type: "burial-mound", age: "stone", cost: { stone: 25 }, buildSeconds: 35 },
  { type: "shaman-tent", age: "stone", cost: { wood: 15, food: 10 }, buildSeconds: 30 },
  { type: "palisade", age: "stone", cost: { wood: 35 }, buildSeconds: 40 },
  { type: "smokehouse", age: "stone", cost: { wood: 25, stone: 5 }, buildSeconds: 35 },
  { type: "elder-lodge", age: "stone", cost: { wood: 30 }, buildSeconds: 45, houses: 3 },
  { type: "stone-circle", age: "stone", cost: { stone: 40 }, buildSeconds: 50 },
  { type: "hide-tanner", age: "stone", cost: { wood: 15, stone: 5 }, buildSeconds: 30 },
  { type: "lumber-camp", age: "stone", cost: { wood: 10, stone: 5 }, buildSeconds: 30, yields: { wood: 10 } },
  { type: "quarry", age: "stone", cost: { wood: 15 }, buildSeconds: 35, yields: { stone: 8 } },
  // bronze
  { type: "farm", age: "bronze", cost: { wood: 30, stone: 10 }, buildSeconds: 50, foodPerDay: 8 },
  { type: "livestock-pen", age: "bronze", cost: { wood: 40, food: 15 }, buildSeconds: 55, foodPerDay: 6 },
  { type: "dock", age: "bronze", cost: { wood: 60, stone: 30 }, buildSeconds: 60 },
  { type: "boat", age: "bronze", cost: { wood: 40 }, buildSeconds: 45 },
  { type: "bronze-forge", age: "bronze", cost: { copper: 20, tin: 10, stone: 20 }, buildSeconds: 60 },
  { type: "copper-mine", age: "bronze", cost: { wood: 30, stone: 20 }, buildSeconds: 50, yields: { copper: 5 } },
  { type: "longhouse", age: "bronze", cost: { wood: 50, stone: 10 }, buildSeconds: 55, houses: 4 },
  { type: "tin-mine", age: "bronze", cost: { wood: 30, stone: 20 }, buildSeconds: 50, yields: { tin: 5 } },
  { type: "kiln", age: "bronze", cost: { stone: 30, wood: 10 }, buildSeconds: 45 },
  { type: "pottery-workshop", age: "bronze", cost: { wood: 25, stone: 15 }, buildSeconds: 50 },
  { type: "weaver", age: "bronze", cost: { wood: 30 }, buildSeconds: 45 },
  { type: "bathhouse", age: "bronze", cost: { stone: 40, copper: 10 }, buildSeconds: 60 },
  { type: "trading-post", age: "bronze", cost: { wood: 45, copper: 5 }, buildSeconds: 55 },
  { type: "bronze-armory", age: "bronze", cost: { copper: 25, tin: 15 }, buildSeconds: 65 },
  { type: "chariot-works", age: "bronze", cost: { wood: 50, copper: 15 }, buildSeconds: 70 },
  { type: "shrine", age: "bronze", cost: { stone: 35, copper: 10 }, buildSeconds: 50 },
  { type: "brewery", age: "bronze", cost: { wood: 35, food: 20 }, buildSeconds: 45 },
  // iron
  { type: "iron-mine", age: "iron", cost: { wood: 40, stone: 30 }, buildSeconds: 60, yields: { iron: 6 } },
  { type: "blacksmith", age: "iron", cost: { wood: 40, iron: 10 }, buildSeconds: 60 },
  { type: "steelworks", age: "iron", cost: { iron: 30, stone: 40 }, buildSeconds: 80, converts: { from: "iron", to: "steel", perDay: 10 } },
  { type: "watchtower", age: "iron", cost: { stone: 50, wood: 30 }, buildSeconds: 70 },
  { type: "barracks", age: "iron", cost: { wood: 50, iron: 20 }, buildSeconds: 75 },
  { type: "roundhouse", age: "iron", cost: { wood: 45, stone: 25 }, buildSeconds: 65, houses: 5 },
  { type: "stone-wall", age: "iron", cost: { stone: 80 }, buildSeconds: 80 },
  { type: "arsenal", age: "iron", cost: { iron: 25, wood: 30 }, buildSeconds: 70 },
  { type: "stable", age: "iron", cost: { wood: 55 }, buildSeconds: 60 },
  { type: "gristmill", age: "iron", cost: { wood: 40, stone: 30 }, buildSeconds: 60 },
  { type: "well", age: "iron", cost: { stone: 35 }, buildSeconds: 45 },
  { type: "moot-hall", age: "iron", cost: { wood: 60, stone: 20 }, buildSeconds: 70 },
  { type: "siege-workshop", age: "iron", cost: { wood: 70, iron: 15 }, buildSeconds: 85 },
  { type: "charcoal-burner", age: "iron", cost: { wood: 45 }, buildSeconds: 50, yields: { coal: 3 } },
  { type: "toll-bridge", age: "iron", cost: { wood: 50, stone: 40 }, buildSeconds: 75 },
  // classical
  { type: "temple", age: "classical", cost: { marble: 40, gold: 10 }, buildSeconds: 100 },
  { type: "amphitheater", age: "classical", cost: { marble: 60, stone: 40 }, buildSeconds: 120, joy: 4 },
  { type: "goldsmith", age: "classical", cost: { gold: 20, wood: 20 }, buildSeconds: 80 },
  { type: "marble-quarry", age: "classical", cost: { wood: 50, stone: 40 }, buildSeconds: 90, yields: { marble: 4 } },
  { type: "forum", age: "classical", cost: { marble: 50, stone: 30 }, buildSeconds: 110 },
  { type: "aqueduct", age: "classical", cost: { stone: 90, marble: 20 }, buildSeconds: 130 },
  { type: "thermae", age: "classical", cost: { marble: 45, stone: 50 }, buildSeconds: 120 },
  { type: "library", age: "classical", cost: { marble: 40, wood: 30 }, buildSeconds: 100 },
  { type: "silver-mine", age: "classical", cost: { wood: 40, stone: 30 }, buildSeconds: 90, yields: { silver: 3 } },
  { type: "gem-cutter", age: "classical", cost: { gems: 10, wood: 25 }, buildSeconds: 85 },
  { type: "mint", age: "classical", cost: { preciousMetals: 15, gold: 10 }, buildSeconds: 95 },
  { type: "hippodrome", age: "classical", cost: { stone: 80, marble: 30 }, buildSeconds: 130, joy: 5 },
  { type: "insula", age: "classical", cost: { stone: 60, wood: 40 }, buildSeconds: 100, houses: 6 },
  { type: "senate-hall", age: "classical", cost: { marble: 70, gold: 15 }, buildSeconds: 140 },
  { type: "sculptors-guild", age: "classical", cost: { marble: 30, stone: 20 }, buildSeconds: 90 },
  { type: "gold-mine", age: "classical", cost: { wood: 40, stone: 30 }, buildSeconds: 90, yields: { gold: 2 } },
  // medieval
  { type: "keep", age: "medieval", cost: { stone: 200, iron: 50 }, buildSeconds: 180 },
  { type: "monastery", age: "medieval", cost: { stone: 80, wood: 60 }, buildSeconds: 140 },
  { type: "windmill", age: "medieval", cost: { wood: 80, stone: 30 }, buildSeconds: 100 },
  { type: "market-hall", age: "medieval", cost: { wood: 60, gold: 20 }, buildSeconds: 110 },
  { type: "castle-wall", age: "medieval", cost: { stone: 150 }, buildSeconds: 160 },
  { type: "barbican", age: "medieval", cost: { stone: 100, iron: 30 }, buildSeconds: 150 },
  { type: "cathedral", age: "medieval", cost: { stone: 120, marble: 60 }, buildSeconds: 200 },
  { type: "guildhall", age: "medieval", cost: { wood: 70, gold: 25 }, buildSeconds: 130 },
  { type: "tavern", age: "medieval", cost: { wood: 60, food: 30 }, buildSeconds: 100, joy: 4 },
  { type: "manor", age: "medieval", cost: { wood: 80, stone: 60 }, buildSeconds: 140, houses: 8 },
  { type: "apothecary", age: "medieval", cost: { wood: 50, silver: 10 }, buildSeconds: 110 },
  { type: "tourney-grounds", age: "medieval", cost: { wood: 70, iron: 20 }, buildSeconds: 120, joy: 4 },
  { type: "scriptorium", age: "medieval", cost: { wood: 55, gold: 15 }, buildSeconds: 115 },
  { type: "watermill", age: "medieval", cost: { wood: 70, stone: 40 }, buildSeconds: 110 },
  { type: "bell-tower", age: "medieval", cost: { stone: 90, copper: 20 }, buildSeconds: 130 },
  // renaissance
  { type: "printing-house", age: "renaissance", cost: { wood: 60, iron: 20 }, buildSeconds: 120 },
  { type: "observatory", age: "renaissance", cost: { stone: 80, gems: 10 }, buildSeconds: 150 },
  { type: "coal-mine", age: "renaissance", cost: { wood: 60, stone: 40 }, buildSeconds: 100, yields: { coal: 5 } },
  { type: "academy", age: "renaissance", cost: { marble: 60, gold: 30 }, buildSeconds: 160 },
  { type: "bank", age: "renaissance", cost: { marble: 50, gold: 40 }, buildSeconds: 140 },
  { type: "opera-house", age: "renaissance", cost: { marble: 70, wood: 50 }, buildSeconds: 160, joy: 6 },
  { type: "cartographers-hall", age: "renaissance", cost: { wood: 50, gems: 5 }, buildSeconds: 120 },
  { type: "glassworks", age: "renaissance", cost: { coal: 20, stone: 40 }, buildSeconds: 110 },
  { type: "clockmaker", age: "renaissance", cost: { iron: 25, gems: 10 }, buildSeconds: 125 },
  { type: "alchemist-lab", age: "renaissance", cost: { silver: 15, coal: 15 }, buildSeconds: 130 },
  { type: "gallery", age: "renaissance", cost: { marble: 40, gold: 20 }, buildSeconds: 120, joy: 4 },
  { type: "townhouse", age: "renaissance", cost: { wood: 60, stone: 50 }, buildSeconds: 130, houses: 8 },
  { type: "anatomy-theater", age: "renaissance", cost: { wood: 55, marble: 25 }, buildSeconds: 135 },
  { type: "gunsmith", age: "renaissance", cost: { iron: 30, coal: 20 }, buildSeconds: 130 },
  { type: "botanical-garden", age: "renaissance", cost: { wood: 45, stone: 25 }, buildSeconds: 105, joy: 6 },
  // industrial
  { type: "factory", age: "industrial", cost: { iron: 100, coal: 50 }, buildSeconds: 200 },
  { type: "railway-yard", age: "industrial", cost: { steel: 80, wood: 40 }, buildSeconds: 180 },
  { type: "oil-derrick", age: "industrial", cost: { steel: 60, wood: 40 }, buildSeconds: 160, yields: { oil: 4 } },
  { type: "gasworks", age: "industrial", cost: { steel: 50, stone: 50 }, buildSeconds: 160, yields: { gas: 3 } },
  { type: "rolling-mill", age: "industrial", cost: { steel: 90, coal: 40 }, buildSeconds: 190 },
  { type: "textile-mill", age: "industrial", cost: { iron: 60, coal: 30 }, buildSeconds: 170 },
  { type: "coking-plant", age: "industrial", cost: { coal: 60, stone: 40 }, buildSeconds: 160 },
  { type: "telegraph-office", age: "industrial", cost: { iron: 40, wood: 30 }, buildSeconds: 140 },
  { type: "tenement", age: "industrial", cost: { stone: 80, iron: 40 }, buildSeconds: 170, houses: 12 },
  { type: "train-station", age: "industrial", cost: { steel: 70, stone: 60 }, buildSeconds: 180 },
  { type: "refinery", age: "industrial", cost: { steel: 70, oil: 30 }, buildSeconds: 190 },
  { type: "newspaper-press", age: "industrial", cost: { steel: 40, wood: 40 }, buildSeconds: 150 },
  { type: "cannery", age: "industrial", cost: { steel: 40, food: 40 }, buildSeconds: 150 },
  { type: "steam-engine-house", age: "industrial", cost: { steel: 60, coal: 50 }, buildSeconds: 180 },
  { type: "exchange", age: "industrial", cost: { marble: 60, gold: 40 }, buildSeconds: 170 },
  // modern
  { type: "power-plant", age: "modern", cost: { steel: 150, coal: 80 }, buildSeconds: 240 },
  { type: "airfield", age: "modern", cost: { steel: 120, oil: 60 }, buildSeconds: 220 },
  { type: "plane", age: "modern", cost: { steel: 60, oil: 30 }, buildSeconds: 90 },
  { type: "reactor", age: "modern", cost: { steel: 200, plutonium: 20 }, buildSeconds: 300, yields: { plutonium: 1 } },
  { type: "broadcast-tower", age: "modern", cost: { steel: 80, gold: 20 }, buildSeconds: 180 },
  { type: "hospital", age: "modern", cost: { steel: 100, gold: 30 }, buildSeconds: 220 },
  { type: "university", age: "modern", cost: { marble: 80, steel: 60 }, buildSeconds: 230 },
  { type: "skyscraper", age: "modern", cost: { steel: 180 }, buildSeconds: 260 },
  { type: "apartment-block", age: "modern", cost: { steel: 100, stone: 80 }, buildSeconds: 220, houses: 16 },
  { type: "highway-depot", age: "modern", cost: { steel: 80, oil: 40 }, buildSeconds: 200 },
  { type: "petrochemical-plant", age: "modern", cost: { steel: 90, oil: 60 }, buildSeconds: 230 },
  { type: "stadium", age: "modern", cost: { steel: 120, stone: 100 }, buildSeconds: 240, joy: 7 },
  { type: "research-lab", age: "modern", cost: { steel: 90, gems: 30 }, buildSeconds: 230 },
  { type: "water-treatment", age: "modern", cost: { steel: 70, stone: 60 }, buildSeconds: 190 },
  { type: "cinema", age: "modern", cost: { steel: 60, gold: 20 }, buildSeconds: 180, joy: 6 },
  { type: "radar-station", age: "modern", cost: { steel: 80, copper: 40 }, buildSeconds: 200 },
  // future
  { type: "fusion-core", age: "future", cost: { plutonium: 50, antimatter: 10 }, buildSeconds: 360 },
  { type: "space-elevator", age: "future", cost: { steel: 500, antimatter: 20 }, buildSeconds: 480 },
  { type: "antimatter-lab", age: "future", cost: { steel: 300, plutonium: 40 }, buildSeconds: 400, yields: { antimatter: 1 } },
  { type: "arcology", age: "future", cost: { steel: 400, gems: 100 }, buildSeconds: 420, houses: 20 },
  { type: "launch-complex", age: "future", cost: { steel: 300, oil: 100 }, buildSeconds: 400 },
  { type: "quantum-computer", age: "future", cost: { gems: 80, plutonium: 30 }, buildSeconds: 380 },
  { type: "ai-nexus", age: "future", cost: { steel: 250, gems: 120 }, buildSeconds: 420 },
  { type: "cryo-vault", age: "future", cost: { steel: 200, gas: 80 }, buildSeconds: 360 },
  { type: "terraformer", age: "future", cost: { steel: 350, antimatter: 15 }, buildSeconds: 460 },
  { type: "nanoforge", age: "future", cost: { steel: 220, plutonium: 30 }, buildSeconds: 380 },
  { type: "skyfarm", age: "future", cost: { steel: 180, food: 200 }, buildSeconds: 340 },
  { type: "graviton-plant", age: "future", cost: { plutonium: 60, antimatter: 10 }, buildSeconds: 440 },
  { type: "holo-theater", age: "future", cost: { steel: 150, gems: 60 }, buildSeconds: 320, joy: 8 },
  { type: "weather-array", age: "future", cost: { steel: 200, copper: 100 }, buildSeconds: 360 },
  { type: "dyson-relay", age: "future", cost: { antimatter: 25, steel: 400 }, buildSeconds: 500 },
  // leisure — one green refuge per age: they produce nothing, settlers idle
  // whole days away in them, and the town is the happier for it
  { type: "dancing-ground", age: "stone", cost: { wood: 15, stone: 10 }, buildSeconds: 25, joy: 3 },
  { type: "garden", age: "bronze", cost: { wood: 30, stone: 10 }, buildSeconds: 40, joy: 4 },
  { type: "bathing-lake", age: "iron", cost: { wood: 20, stone: 30 }, buildSeconds: 50, joy: 4 },
  { type: "pleasure-garden", age: "classical", cost: { marble: 30, wood: 30 }, buildSeconds: 80, joy: 5 },
  { type: "village-green", age: "medieval", cost: { wood: 40, stone: 20 }, buildSeconds: 70, joy: 5 },
  { type: "fountain-plaza", age: "renaissance", cost: { marble: 50, silver: 10 }, buildSeconds: 100, joy: 6 },
  { type: "city-park", age: "industrial", cost: { wood: 80, iron: 20 }, buildSeconds: 120, joy: 7 },
  { type: "funfair", age: "modern", cost: { steel: 60, gold: 15 }, buildSeconds: 160, joy: 8 },
  { type: "gravity-garden", age: "future", cost: { steel: 100, gems: 20 }, buildSeconds: 220, joy: 9 },
];

const byType = new Map([...BUILDINGS, ...WONDERS].map((b) => [b.type, b]));

export function buildingSpec(type: string): BuildingSpec | undefined {
  return byType.get(type);
}
