import type { CivId, CivSpec } from "./types";

/** Six civilizations — total flavor: names, architecture, boats, feed voice. */
export const CIVS: Record<CivId, CivSpec> = {
  roman: {
    id: "roman",
    label: "Roman",
    nameBank: [
      "Marcus", "Livia", "Gaius", "Julia", "Titus", "Octavia", "Quintus",
      "Claudia", "Lucius", "Aurelia", "Decimus", "Antonia", "Cassius",
      "Flavia", "Publius", "Valeria", "Severus", "Camilla", "Tiberius",
      "Drusilla", "Atticus", "Sabina",
    ],
    islandNames: ["Nova Roma", "Portus Solis", "Insula Aurea", "Mons Victoria", "Litus Aquilae", "Castra Maris"],
    accent: "#a03333",
    architecture: { roof: "gabled", primary: "#d9cbb2", trim: "#a03333" },
    boat: { hull: "#7a5a3a", sail: "#c8b89a", shape: "galley" },
    voice: {
      build: "By decree of the forum, {name} raises a {building}.",
      birth: "The household rejoices — {name} is born a citizen.",
      death: "The forum falls silent. {name} has crossed the Styx.",
      ageUp: "{island} proclaims a new era. The legions of progress march on.",
    },
  },
  greek: {
    id: "greek",
    label: "Greek",
    nameBank: [
      "Alexios", "Thalia", "Nikos", "Elena", "Theron", "Kalliope", "Dimitri",
      "Penelope", "Stavros", "Ariadne", "Leonidas", "Daphne", "Hektor",
      "Melina", "Petros", "Xanthe", "Aristos", "Ione", "Basil", "Zoe",
      "Philon", "Kassandra",
    ],
    islandNames: ["Thalassia", "Nea Delos", "Argyros", "Petra Leuka", "Anemoessa", "Kymatos"],
    accent: "#2563a8",
    architecture: { roof: "flat", primary: "#eee9dd", trim: "#2563a8" },
    boat: { hull: "#3a4a5a", sail: "#f0ead8", shape: "galley" },
    voice: {
      build: "With reason and rope, {name} completes the {building}.",
      birth: "The muses sing — {name} draws first breath.",
      death: "An owl calls at dusk. {name} has gone to the fields of asphodel.",
      ageUp: "{island} steps into a brighter age, as the philosophers foretold.",
    },
  },
  egyptian: {
    id: "egyptian",
    label: "Egyptian",
    nameBank: [
      "Amenemhat", "Nefertari", "Khnum", "Meritamen", "Ramose", "Isetnofret",
      "Huy", "Tiye", "Paneb", "Henutmire", "Kawab", "Nubemhet", "Djedefre",
      "Ahmose", "Baketamun", "Senusret", "Mutnedjmet", "Ptahmose", "Satiah",
      "Ineni", "Naunakhte", "Userhat",
    ],
    islandNames: ["Ta-Meri", "Iunu of the Sea", "Waset Rising", "Kem Shore", "Sekhet Aaru", "Menefer Sands"],
    accent: "#c2921e",
    architecture: { roof: "stepped", primary: "#e0c98f", trim: "#c2921e" },
    boat: { hull: "#c9b280", sail: "#f5eeda", shape: "reed" },
    voice: {
      build: "Under the eye of Ra, {name} finishes the {building}.",
      birth: "The Nile of this island rises — {name} is born.",
      death: "{name} sails now on the barque of the west.",
      ageUp: "{island} ascends, and the scribes carve a new dynasty.",
    },
  },
  norse: {
    id: "norse",
    label: "Norse",
    nameBank: [
      "Bjorn", "Astrid", "Leif", "Freya", "Erik", "Sigrid", "Olaf", "Ingrid",
      "Ragnar", "Helga", "Sven", "Thora", "Gunnar", "Solveig", "Harald",
      "Runa", "Torstein", "Ylva", "Knut", "Embla", "Vidar", "Saga",
    ],
    islandNames: ["Jokulholm", "Skjaldey", "Vindheim", "Barufjord", "Hrafnsker", "Eldstrond"],
    accent: "#4a7d8c",
    architecture: { roof: "gabled", primary: "#6b5844", trim: "#4a7d8c" },
    boat: { hull: "#4a3a2a", sail: "#9db3b8", shape: "longship" },
    voice: {
      build: "Timber sings under the axe — {name} has raised the {building}.",
      birth: "A new saga begins: {name} is born beneath the pale sky.",
      death: "Ravens carry the tale. {name} feasts tonight in distant halls.",
      ageUp: "The skalds of {island} will sing of this age for a thousand winters.",
    },
  },
  japanese: {
    id: "japanese",
    label: "Japanese",
    nameBank: [
      "Hiroshi", "Yuki", "Kenji", "Sakura", "Takeshi", "Hana", "Ryo",
      "Aiko", "Daisuke", "Emi", "Sho", "Rin", "Kaito", "Mei", "Haruto",
      "Naoko", "Renjiro", "Chiyo", "Isamu", "Tomoe", "Masaru", "Fumiko",
    ],
    islandNames: ["Shimakaze", "Hoshijima", "Takamori", "Umi-no-Sato", "Kagerou", "Asahi-shima"],
    accent: "#b0413e",
    architecture: { roof: "pagoda", primary: "#e8ddc8", trim: "#b0413e" },
    boat: { hull: "#5a4632", sail: "#f2ead9", shape: "junk" },
    voice: {
      build: "With patient hands, {name} sets the last beam of the {building}.",
      birth: "A blossom opens — {name} is born to the island.",
      death: "The lanterns are lit for {name}, who walks the quiet road.",
      ageUp: "{island} greets a new dawn; the old ways bow, and the new ascend.",
    },
  },
  aztec: {
    id: "aztec",
    label: "Aztec",
    nameBank: [
      "Itzel", "Cuauhtemoc", "Xochitl", "Tlaloc", "Citlali", "Moctezuma",
      "Nenetl", "Tochtli", "Izel", "Yaotl", "Metztli", "Coyotl", "Zyanya",
      "Ehecatl", "Tayanna", "Necalli", "Atzi", "Ollin", "Teyacapan",
      "Matlal", "Xipil", "Anacaona",
    ],
    islandNames: ["Aztlan Rising", "Teocalli Shore", "Mictlan Reef", "Tonatiuh Isle", "Coatepec", "Xochimilca"],
    accent: "#2e8b57",
    architecture: { roof: "stepped", primary: "#c9a66b", trim: "#2e8b57" },
    boat: { hull: "#6b4f2a", sail: "#dfd3b0", shape: "canoe" },
    voice: {
      build: "The fifth sun shines on {name}, who has completed the {building}.",
      birth: "Drums sound from the plaza — {name} enters the world.",
      death: "{name} has followed the hummingbird south. The island remembers.",
      ageUp: "{island} climbs the great pyramid of time to a higher step.",
    },
  },
  mauryan: {
    id: "mauryan",
    label: "Mauryan",
    nameBank: [
      "Ashoka", "Chandragupta", "Bindusara", "Kautilya", "Devika", "Padma",
      "Arjuna", "Meera", "Ravi", "Lakshmi", "Vikrama", "Tara", "Ananda",
      "Sita", "Dhruva", "Indrani", "Sanjaya", "Kiran", "Rohana", "Nisha",
      "Amara", "Vasanti",
    ],
    islandNames: ["Pataliputra Isle", "Taxila Shore", "Ujjain Rock", "Sanchi Crown", "Nalanda Reach", "Vaishali Sands"],
    accent: "#d97e21",
    architecture: { roof: "domed", primary: "#e6d4a8", trim: "#d97e21" },
    boat: { hull: "#8a6a3f", sail: "#f0e2bd", shape: "reed" },
    voice: {
      build: "As the edicts counsel, {name} completes the {building}.",
      birth: "A lotus opens — {name} is born to the island.",
      death: "The wheel turns. {name} walks the far path now.",
      ageUp: "{island} ascends, and the news is carved in stone for all to read.",
    },
  },
  mongol: {
    id: "mongol",
    label: "Mongol",
    nameBank: [
      "Temujin", "Borte", "Jochi", "Chagatai", "Ogedei", "Tolui", "Subutai",
      "Jebe", "Khulan", "Hoelun", "Kublai", "Mongke", "Batu", "Sorkhaqtani",
      "Altani", "Naran", "Bataar", "Chuluun", "Oyuun", "Saran", "Erdene",
      "Yesugen",
    ],
    islandNames: ["Karakorum Rock", "Onon Vale", "Kherlen Reach", "Altai Crag", "Orkhon Isle", "Khangai Shore"],
    accent: "#4a7ec2",
    architecture: { roof: "domed", primary: "#cbb9a2", trim: "#4a7ec2" },
    boat: { hull: "#5c4a33", sail: "#e8e0ce", shape: "canoe" },
    voice: {
      build: "Swift as a steppe wind, {name} raises the {building}.",
      birth: "Under the eternal blue sky, {name} is born to the horde.",
      death: "The banner dips. {name} rides beyond the horizon.",
      ageUp: "{island} thunders into a new age — the horde does not slow.",
    },
  },
};
